name: MotoGP Pipeline - Incremental

on:
  workflow_dispatch:  # trigger manual
    inputs:
      year:
        description: 'Año a ingestar (ej: 2026)'
        required: true
        default: '2026'

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install pandas snowflake-connector-python python-dotenv

      - name: Ejecutar ingesta Bronze
        env:
          SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:      ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE:  DEV_MOTOGP_BRONZE_DB
          SNOWFLAKE_SCHEMA:    RAW
        run: |
          python ingest_motogp.py \
            --root-dir . \
            --only results,sessions \
            --database DEV_MOTOGP_BRONZE_DB \
            --schema RAW \
            --warehouse ${{ secrets.SNOWFLAKE_WAREHOUSE }}

      - name: Trigger dbt Cloud Job
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: Token ${{ secrets.DBT_CLOUD_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"cause": "Triggered by GitHub Actions post-GP"}' \
            https://al725.us1.dbt.com/api/v2/accounts/70471823560048/jobs/70471823598683/run/)
          
          echo "HTTP Status: $response"
          cat response.json
          
          if [ "$response" != "200" ]; then
            echo "Error triggering dbt Cloud job"
            exit 1
          fi

      - name: Verificar estado del Job
        run: |
          run_id=$(cat response.json | python3 -c "import sys,json; print(json.load(sys.stdin)['data']['id'])")
          echo "dbt Cloud Run ID: $run_id"
          echo "Sigue el progreso en: https://al725.us1.dbt.com/deploy/70471823560048/runs/$run_id"
